Imports BACSOFT.Db.SqlHelper

Public Class frmTongHopXK

    Private Sub frmTongHopXK_Load(sender As Object, e As System.EventArgs) Handles Me.Load
        tbNam.EditValue = Today.Year
        LoadPhongBan()
    End Sub

    Public Sub LoadPhongBan()
        Dim tb As DataTable = ExecuteSQLDataTable("SELECT ID,Ten FROM DEPATMENT ORDER BY ID")
        If Not tb Is Nothing Then
            rcbPhong.DataSource = tb
        Else
            ShowBaoLoi(LoiNgoaiLe)
        End If

    End Sub



    Private Sub btXem_ItemClick(sender As System.Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles btXem.ItemClick
        If tabXK.SelectedTabPage Is tabCachCu Then
            XemCachCu()
        Else
            XemCachMoi()
        End If
    End Sub

    Public Sub XemCachCu()
        Dim sql As String = ""
        '--===========Doanh thu của từng kinh doanh"
        sql &= " SELECT IDTakeCare, [01] , [02], [03], [04], [05], "
        sql &= " 	[06], [07], [08], [09], [10], [11], [12],"
        sql &= " (ISNULL([01],0)+ ISNULL([02],0)+ ISNULL([03],0)+ ISNULL([04],0)+ ISNULL([05],0)+ ISNULL([06],0)+ ISNULL([07],0)+ ISNULL([08],0)+ ISNULL([09],0)+ ISNULL([10],0)+ ISNULL([11],0)+ ISNULL([12],0))Tong,"
        sql &= " (0) AS AZ"
        sql &= " INTO #tbDoanhThu"
        sql &= " FROM "
        sql &= " (SELECT IDTakeCare, right(YearMonth,2)Thang,(TongBan/1000000)TongBan"
        sql &= " 	FROM V_XuatKhoKetQuaTH "
        sql &= "    WHERE YearMonth like '" & tbNam.EditValue.ToString.Substring(2, 2) & "%') p"
        sql &= " PIVOT"
        sql &= " ("
        sql &= " SUM (TongBan)"
        sql &= " FOR Thang IN"
        sql &= " ( [01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12] )"
        sql &= " ) AS pvt"
        sql &= " "
        '--===========Doanh thu của phòng"
        sql &= " "
        sql &= " SELECT NULL AS IDTakeCare,N'   DT.'+ ISNULL(DEPATMENT.Ten,N'')Ten, SUM([01]) AS [01] ,SUM([02]) AS [02],SUM([03]) AS [03],SUM([04]) AS [04],SUM([05]) AS [05], "
        sql &= " 	SUM([06]) AS [06],SUM([07]) AS [07],SUM([08]) AS [08],SUM([09]) AS [09],SUM([10]) AS [10],SUM([11]) AS [11],SUM([12]) AS [12],SUM(Tong) AS Tong"
        sql &= " INTO #tbDoanhThuPhong"
        sql &= " FROM #tbDoanhThu"
        sql &= " INNER JOIN NHANSU ON NHANSU.ID=#tbDoanhThu.IDTakeCare"
        sql &= " INNER JOIN DEPATMENT ON DEPATMENT.ID=NHANSU.IDDepatment"
        sql &= " Group By Depatment.Ten"
        sql &= " "
        ' --========================================="
        sql &= " "
        sql &= " SELECT IDTakeCare, [01], [02], [03], [04], [05], [06], "
        sql &= " 	[07], [08], [09], [10], [11], [12],"
        sql &= " (ISNULL([01],0)+ ISNULL([02],0)+ ISNULL([03],0)+ ISNULL([04],0)+ ISNULL([05],0)+ ISNULL([06],0)+ ISNULL([07],0)+ ISNULL([08],0)+ ISNULL([09],0)+ ISNULL([10],0)+ ISNULL([11],0)+ ISNULL([12],0))Tong,"
        sql &= " (1) AS AZ"
        sql &= " INTO #tbLoiNhuan"
        sql &= " FROM "
        sql &= " (SELECT IDTakeCare, right(YearMonth,2)Thang,((ISNULL(TongBan,0)-ISNULL(TongGoc,0)-ISNULL(TongChiPhi,0)-ISNULL(TongChietKhau,0))/1000000)LoiNhuan "
        sql &= " 	FROM V_XuatKhoKetQuaTH "
        sql &= "    WHERE YearMonth like '" & tbNam.EditValue.ToString.Substring(2, 2) & "%') p"
        sql &= " PIVOT"
        sql &= " ("
        sql &= " SUM (LoiNhuan)"
        sql &= " FOR Thang IN"
        sql &= " ( [01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12] )"
        sql &= " ) AS  pvtLoiNhuan"
        '--=================Lợi nhuận phòng========================"
        sql &= " SELECT NULL AS IDTakeCare,N'   LN.'+ ISNULL(DEPATMENT.Ten,N'')Ten, SUM([01]) AS [01] ,SUM([02]) AS [02],SUM([03]) AS [03],SUM([04]) AS [04],SUM([05]) AS [05], "
        sql &= " 	SUM([06]) AS [06],SUM([07]) AS [07],SUM([08]) AS [08],SUM([09]) AS [09],SUM([10]) AS [10],SUM([11]) AS [11],SUM([12]) AS [12],SUM(Tong) AS Tong"
        sql &= " INTO #tbLoiNhuanPhong"
        sql &= " FROM #tbLoiNhuan"
        sql &= " INNER JOIN NHANSU ON NHANSU.ID=#tbLoiNhuan.IDTakeCare"
        sql &= " INNER JOIN DEPATMENT ON DEPATMENT.ID=NHANSU.IDDepatment"
        sql &= " Group By Depatment.Ten"
        sql &= " "
        ' --========================================="
        sql &= " SELECT IDTakeCare, [01], [02], [03], [04], [05], [06], "
        sql &= " 	[07], [08], [09], [10], [11], [12],"
        sql &= " (ISNULL([01],0)+ ISNULL([02],0)+ ISNULL([03],0)+ ISNULL([04],0)+ ISNULL([05],0)+ ISNULL([06],0)+ ISNULL([07],0)+ ISNULL([08],0)+ ISNULL([09],0)+ ISNULL([10],0)+ ISNULL([11],0)+ ISNULL([12],0))Tong,"
        sql &= " (1) AS AZ"
        sql &= " INTO #tbChietKhau"
        sql &= " FROM "
        sql &= " (SELECT IDTakeCare, right(YearMonth,2)Thang,(ISNULL(TongChietKhau,0)/1000000)ChietKhau "
        sql &= " 	FROM V_XuatKhoKetQuaTH "
        sql &= "    WHERE YearMonth like '" & tbNam.EditValue.ToString.Substring(2, 2) & "%') p"
        sql &= " PIVOT"
        sql &= " ("
        sql &= " SUM (ChietKhau)"
        sql &= " FOR Thang IN"
        sql &= " ( [01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12] )"
        sql &= " ) AS  pvtChietKhau"
        ' --=================Chiết khấu phòng========================"
        sql &= " SELECT NULL AS IDTakeCare,N'   CK.'+ ISNULL(DEPATMENT.Ten,N'')Ten, SUM([01]) AS [01] ,SUM([02]) AS [02],SUM([03]) AS [03],SUM([04]) AS [04],SUM([05]) AS [05], "
        sql &= " 	SUM([06]) AS [06],SUM([07]) AS [07],SUM([08]) AS [08],SUM([09]) AS [09],SUM([10]) AS [10],SUM([11]) AS [11],SUM([12]) AS [12],SUM(Tong) AS Tong"
        sql &= " INTO #tbChietKhauPhong"
        sql &= " FROM #tbChietKhau"
        sql &= " INNER JOIN NHANSU ON NHANSU.ID=#tbChietKhau.IDTakeCare"
        sql &= " INNER JOIN DEPATMENT ON DEPATMENT.ID=NHANSU.IDDepatment"
        sql &= " Group By Depatment.Ten"
        ' --========================================="
        sql &= " "
        sql &= " SELECT NULL AS IDTakeCare, N'Tổng LN' AS Ten, SUM([01]) AS [01] , SUM([02]) AS [02] , SUM([03]) AS [03] , SUM([04]) AS [04] , "
        sql &= " 	SUM([05]) AS [05] , SUM([06]) AS [06] , SUM([07]) AS [07] , SUM([08]) AS [08] , SUM([09]) AS [09] , "
        sql &= " 	SUM([10]) AS [10] , SUM([11]) AS [11] , SUM([12]) AS [12],Sum(Tong)AS Tong"
        sql &= " INTO #tbTongLN"
        sql &= " FROM #tbLoiNhuan"
        ' --========================================="
        sql &= " SELECT NULL AS IDTakeCare, N'Tổng chi phí' AS Ten, [01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12],"
        sql &= " (ISNULL([01],0)+ ISNULL([02],0)+ ISNULL([03],0)+ ISNULL([04],0)+ ISNULL([05],0)+ ISNULL([06],0)+ ISNULL([07],0)+ ISNULL([08],0)+ ISNULL([09],0)+ ISNULL([10],0)+ ISNULL([11],0)+ ISNULL([12],0))Tong"
        sql &= " INTO #tbChiPhi"
        sql &= " FROM ("
        sql &= " 	SELECT SUM(ChiPhi)ChiPhi,Thang"
        sql &= " 	FROM("
        sql &= " 		select (sum(sotien)/1000000)ChiPhi,SubString(SoPhieu,3,2)Thang from chi INNER JOIN MUCDICHTHUCHI ON CHI.MucDich=MUCDICHTHUCHI.ID AND MUCDICHTHUCHI.ChiPhiMatDi=1 where sophieu like '" & tbNam.EditValue.ToString.Substring(2, 2) & "%'  group by SubString(SoPhieu,3,2) "
        sql &= " 		UNION ALL"
        sql &= " 		select (sum(sotien)/1000000)ChiPhi,SubString(SoPhieu,3,2)Thang from UNC INNER JOIN MUCDICHTHUCHI ON UNC.MucDich=MUCDICHTHUCHI.ID AND MUCDICHTHUCHI.ChiPhiMatDi=1 where sophieu like '" & tbNam.EditValue.ToString.Substring(2, 2) & "%'  group by SubString(SoPhieu,3,2) "
        sql &= " 	)tb"
        sql &= " 	GROUP BY Thang) p"
        sql &= " PIVOT"
        sql &= " ("
        sql &= " SUM (ChiPhi)"
        sql &= " FOR Thang IN"
        sql &= " ( [01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12] )"
        sql &= " ) AS  pvtChiPhi"
        ' --========================================="
        sql &= " SELECT tb.IDTakeCare,Ten,[01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12],"
        sql &= " 	(ISNULL([01],0)+ ISNULL([02],0)+ ISNULL([03],0)+ ISNULL([04],0)+ ISNULL([05],0)+ ISNULL([06],0)+ ISNULL([07],0)+ ISNULL([08],0)+ ISNULL([09],0)+ ISNULL([10],0)+ ISNULL([11],0)+ ISNULL([12],0))Tong"
        sql &= " INTO #tbLoiNhuanThuc"
        sql &= " FROM"
        sql &= " 	(SELECT NULL AS IDTakeCare, N'Tổng lợi nhuận' AS Ten,(ISNULL(#tbTongLN.[01],0)-ISNULL(#tbChiPhi.[01],0)) AS [01],"
        sql &= " 	(ISNULL(#tbTongLN.[02],0)-ISNULL(#tbChiPhi.[02],0)) AS [02],(ISNULL(#tbTongLN.[03],0)-ISNULL(#tbChiPhi.[03],0)) AS [03],"
        sql &= " 	(ISNULL(#tbTongLN.[04],0)-ISNULL(#tbChiPhi.[04],0)) AS [04],(ISNULL(#tbTongLN.[05],0)-ISNULL(#tbChiPhi.[05],0)) AS [05],"
        sql &= " 	(ISNULL(#tbTongLN.[06],0)-ISNULL(#tbChiPhi.[06],0)) AS [06],(ISNULL(#tbTongLN.[07],0)-ISNULL(#tbChiPhi.[07],0)) AS [07],"
        sql &= " 	(ISNULL(#tbTongLN.[08],0)-ISNULL(#tbChiPhi.[08],0)) AS [08],(ISNULL(#tbTongLN.[09],0)-ISNULL(#tbChiPhi.[09],0)) AS [09],"
        sql &= " 	(ISNULL(#tbTongLN.[10],0)-ISNULL(#tbChiPhi.[10],0)) AS [10],(ISNULL(#tbTongLN.[11],0)-ISNULL(#tbChiPhi.[11],0)) AS [11],"
        sql &= " 	(ISNULL(#tbTongLN.[12],0)-ISNULL(#tbChiPhi.[12],0)) AS [12]"
        sql &= " 	FROM #tbTongLN"
        sql &= " 	INNER JOIN #tbChiPhi ON ISNULL(#tbTongLN.IDTakeCare,1) = ISNULL(#tbChiPhi.IDTakeCare,1))tb"

        sql &= " SELECT tb.IDTakeCare,(CASE AZ WHEN 0 THEN NHANSU.Ten ELSE N' ' END)Ten,[01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12],Tong"
        sql &= " INTO #tbM"
        sql &= " FROM"
        sql &= " ("
        sql &= " SELECT * FROm #tbDoanhThu"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbLoiNhuan"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbChietKhau"
        sql &= " )tb"
        sql &= " LEFT JOIN NHANSU ON CONVERT(Nvarchar,NHANSU.ID)=tb.IDTakeCare"
        sql &= " ORDER BY tb.IDTakeCare,AZ"

        sql &= " SELECT * FROM #tbM"
        sql &= " UNION ALL"
        sql &= " select * FROM #tbDoanhThuPhong"
        sql &= " UNION ALL"
        sql &= " SELECT NULL AS IDTakeCare,N'Tổng doanh thu' AS Ten, SUM([01]) AS [01] , SUM([02]) AS [02] , SUM([03]) AS [03] , SUM([04]) AS [04] , "
        sql &= " 	SUM([05]) AS [05] , SUM([06]) AS [06] , SUM([07]) AS [07] , SUM([08]) AS [08] , SUM([09]) AS [09] , "
        sql &= " 	SUM([10]) AS [10] , SUM([11]) AS [11] , SUM([12]) AS [12],SUM(Tong)Tong"
        sql &= " FROM #tbDoanhThu"
        sql &= " UNION ALL"
        sql &= " select * FROM #tbLoiNhuanPhong"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbTongLN"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbChietKhauPhong"
        sql &= " UNION ALL"
        sql &= " SELECT NULL AS IDTakeCare,N'Tổng chiết khấu' AS Ten, SUM([01]) AS [01] , SUM([02]) AS [02] , SUM([03]) AS [03] , SUM([04]) AS [04] , "
        sql &= " 	SUM([05]) AS [05] , SUM([06]) AS [06] , SUM([07]) AS [07] , SUM([08]) AS [08] , SUM([09]) AS [09] , "
        sql &= " 	SUM([10]) AS [10] , SUM([11]) AS [11] , SUM([12]) AS [12],SUM(Tong)Tong"
        sql &= " FROM #tbChietKhau"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbChiPhi"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbLoiNhuanThuc"

        sql &= " DROP table #tbM"
        sql &= " DROP table #tbDoanhThu"
        sql &= " DROP table #tbDoanhThuPhong"
        sql &= " DROP table #tbLoiNhuan"
        sql &= " DROP table #tbLoiNhuanPhong"
        sql &= " DROP table #tbChietKhau"
        sql &= " DROP table #tbChietKhauPhong"
        sql &= " DROP table #tbChiPhi"
        sql &= " DROP table #tbTongLN"
        sql &= " DROP table #tbLoiNhuanThuc "

        Dim tb As DataTable = ExecuteSQLDataTable(sql)
        If Not tb Is Nothing Then
            gdv.DataSource = tb
        Else
            ShowBaoLoi(LoiNgoaiLe)
        End If
    End Sub

    Public Sub XemCachMoi()
        Dim sql As String = ""
        '--===========Doanh thu của từng kinh doanh"
        sql &= " SELECT IDTakeCare, [01] , [02], [03], [04], [05], "
        sql &= " 	[06], [07], [08], [09], [10], [11], [12],"
        sql &= " (ISNULL([01],0)+ ISNULL([02],0)+ ISNULL([03],0)+ ISNULL([04],0)+ ISNULL([05],0)+ ISNULL([06],0)+ ISNULL([07],0)+ ISNULL([08],0)+ ISNULL([09],0)+ ISNULL([10],0)+ ISNULL([11],0)+ ISNULL([12],0))Tong,"
        sql &= " (0) AS AZ"
        sql &= " INTO #tbDoanhThu"
        sql &= " FROM "
        sql &= " (SELECT IDTakeCare, right(YearMonth,2)Thang,(TongBan/1000000)TongBan"
        sql &= " 	FROM View_KetQuaXKTHTheoGiaNhapTB "
        sql &= "    WHERE YearMonth like '" & tbNam.EditValue.ToString.Substring(2, 2) & "%') p"
        sql &= " PIVOT"
        sql &= " ("
        sql &= " SUM (TongBan)"
        sql &= " FOR Thang IN"
        sql &= " ( [01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12] )"
        sql &= " ) AS pvt"
        sql &= " "
        '--===========Doanh thu của phòng"
        sql &= " "
        sql &= " SELECT NULL AS IDTakeCare,N'   DT.'+ ISNULL(DEPATMENT.Ten,N'')Ten, SUM([01]) AS [01] ,SUM([02]) AS [02],SUM([03]) AS [03],SUM([04]) AS [04],SUM([05]) AS [05], "
        sql &= " 	SUM([06]) AS [06],SUM([07]) AS [07],SUM([08]) AS [08],SUM([09]) AS [09],SUM([10]) AS [10],SUM([11]) AS [11],SUM([12]) AS [12],SUM(Tong) AS Tong"
        sql &= " INTO #tbDoanhThuPhong"
        sql &= " FROM #tbDoanhThu"
        sql &= " INNER JOIN NHANSU ON NHANSU.ID=#tbDoanhThu.IDTakeCare"
        sql &= " INNER JOIN DEPATMENT ON DEPATMENT.ID=NHANSU.IDDepatment"
        sql &= " Group By Depatment.Ten"
        sql &= " "
        ' --========================================="
        sql &= " "
        sql &= " SELECT IDTakeCare, [01], [02], [03], [04], [05], [06], "
        sql &= " 	[07], [08], [09], [10], [11], [12],"
        sql &= " (ISNULL([01],0)+ ISNULL([02],0)+ ISNULL([03],0)+ ISNULL([04],0)+ ISNULL([05],0)+ ISNULL([06],0)+ ISNULL([07],0)+ ISNULL([08],0)+ ISNULL([09],0)+ ISNULL([10],0)+ ISNULL([11],0)+ ISNULL([12],0))Tong,"
        sql &= " (1) AS AZ"
        sql &= " INTO #tbLoiNhuan"
        sql &= " FROM "
        sql &= " (SELECT IDTakeCare, right(YearMonth,2)Thang,((ISNULL(TongBan,0)-ISNULL(TongGoc,0)-ISNULL(TongChiPhi,0)-ISNULL(TongChietKhau,0))/1000000)LoiNhuan "
        sql &= " 	FROM View_KetQuaXKTHTheoGiaNhapTB "
        sql &= "    WHERE YearMonth like '" & tbNam.EditValue.ToString.Substring(2, 2) & "%') p"
        sql &= " PIVOT"
        sql &= " ("
        sql &= " SUM (LoiNhuan)"
        sql &= " FOR Thang IN"
        sql &= " ( [01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12] )"
        sql &= " ) AS  pvtLoiNhuan"
        '--=================Lợi nhuận phòng========================"
        sql &= " SELECT NULL AS IDTakeCare,N'   LN.'+ ISNULL(DEPATMENT.Ten,N'')Ten, SUM([01]) AS [01] ,SUM([02]) AS [02],SUM([03]) AS [03],SUM([04]) AS [04],SUM([05]) AS [05], "
        sql &= " 	SUM([06]) AS [06],SUM([07]) AS [07],SUM([08]) AS [08],SUM([09]) AS [09],SUM([10]) AS [10],SUM([11]) AS [11],SUM([12]) AS [12],SUM(Tong) AS Tong"
        sql &= " INTO #tbLoiNhuanPhong"
        sql &= " FROM #tbLoiNhuan"
        sql &= " INNER JOIN NHANSU ON NHANSU.ID=#tbLoiNhuan.IDTakeCare"
        sql &= " INNER JOIN DEPATMENT ON DEPATMENT.ID=NHANSU.IDDepatment"
        sql &= " Group By Depatment.Ten"
        sql &= " "
        ' --========================================="
        sql &= " SELECT IDTakeCare, [01], [02], [03], [04], [05], [06], "
        sql &= " 	[07], [08], [09], [10], [11], [12],"
        sql &= " (ISNULL([01],0)+ ISNULL([02],0)+ ISNULL([03],0)+ ISNULL([04],0)+ ISNULL([05],0)+ ISNULL([06],0)+ ISNULL([07],0)+ ISNULL([08],0)+ ISNULL([09],0)+ ISNULL([10],0)+ ISNULL([11],0)+ ISNULL([12],0))Tong,"
        sql &= " (1) AS AZ"
        sql &= " INTO #tbChietKhau"
        sql &= " FROM "
        sql &= " (SELECT IDTakeCare, right(YearMonth,2)Thang,(ISNULL(TongChietKhau,0)/1000000)ChietKhau "
        sql &= " 	FROM View_KetQuaXKTHTheoGiaNhapTB "
        sql &= "    WHERE YearMonth like '" & tbNam.EditValue.ToString.Substring(2, 2) & "%') p"
        sql &= " PIVOT"
        sql &= " ("
        sql &= " SUM (ChietKhau)"
        sql &= " FOR Thang IN"
        sql &= " ( [01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12] )"
        sql &= " ) AS  pvtChietKhau"
        ' --=================Chiết khấu phòng========================"
        sql &= " SELECT NULL AS IDTakeCare,N'   CK.'+ ISNULL(DEPATMENT.Ten,N'')Ten, SUM([01]) AS [01] ,SUM([02]) AS [02],SUM([03]) AS [03],SUM([04]) AS [04],SUM([05]) AS [05], "
        sql &= " 	SUM([06]) AS [06],SUM([07]) AS [07],SUM([08]) AS [08],SUM([09]) AS [09],SUM([10]) AS [10],SUM([11]) AS [11],SUM([12]) AS [12],SUM(Tong) AS Tong"
        sql &= " INTO #tbChietKhauPhong"
        sql &= " FROM #tbChietKhau"
        sql &= " INNER JOIN NHANSU ON NHANSU.ID=#tbChietKhau.IDTakeCare"
        sql &= " INNER JOIN DEPATMENT ON DEPATMENT.ID=NHANSU.IDDepatment"
        sql &= " Group By Depatment.Ten"
        ' --========================================="
        sql &= " "
        sql &= " SELECT NULL AS IDTakeCare, N'Tổng LN' AS Ten, SUM([01]) AS [01] , SUM([02]) AS [02] , SUM([03]) AS [03] , SUM([04]) AS [04] , "
        sql &= " 	SUM([05]) AS [05] , SUM([06]) AS [06] , SUM([07]) AS [07] , SUM([08]) AS [08] , SUM([09]) AS [09] , "
        sql &= " 	SUM([10]) AS [10] , SUM([11]) AS [11] , SUM([12]) AS [12],Sum(Tong)AS Tong"
        sql &= " INTO #tbTongLN"
        sql &= " FROM #tbLoiNhuan"
        ' --========================================="
        sql &= " SELECT NULL AS IDTakeCare, N'Tổng chi phí' AS Ten, [01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12],"
        sql &= " (ISNULL([01],0)+ ISNULL([02],0)+ ISNULL([03],0)+ ISNULL([04],0)+ ISNULL([05],0)+ ISNULL([06],0)+ ISNULL([07],0)+ ISNULL([08],0)+ ISNULL([09],0)+ ISNULL([10],0)+ ISNULL([11],0)+ ISNULL([12],0))Tong"
        sql &= " INTO #tbChiPhi"
        sql &= " FROM ("
        sql &= " 	SELECT SUM(ChiPhi)ChiPhi,Thang"
        sql &= " 	FROM("
        sql &= " 		select (sum(sotien)/1000000)ChiPhi,SubString(SoPhieu,3,2)Thang from chi INNER JOIN MUCDICHTHUCHI ON CHI.MucDich=MUCDICHTHUCHI.ID AND MUCDICHTHUCHI.ChiPhiMatDi=1 where sophieu like '" & tbNam.EditValue.ToString.Substring(2, 2) & "%'  group by SubString(SoPhieu,3,2) "
        sql &= " 		UNION ALL"
        sql &= " 		select (sum(sotien)/1000000)ChiPhi,SubString(SoPhieu,3,2)Thang from UNC INNER JOIN MUCDICHTHUCHI ON UNC.MucDich=MUCDICHTHUCHI.ID AND MUCDICHTHUCHI.ChiPhiMatDi=1 where sophieu like '" & tbNam.EditValue.ToString.Substring(2, 2) & "%'  group by SubString(SoPhieu,3,2) "
        sql &= " 	)tb"
        sql &= " 	GROUP BY Thang) p"
        sql &= " PIVOT"
        sql &= " ("
        sql &= " SUM (ChiPhi)"
        sql &= " FOR Thang IN"
        sql &= " ( [01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12] )"
        sql &= " ) AS  pvtChiPhi"
        ' --========================================="
        sql &= " SELECT tb.IDTakeCare,Ten,[01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12],"
        sql &= " 	(ISNULL([01],0)+ ISNULL([02],0)+ ISNULL([03],0)+ ISNULL([04],0)+ ISNULL([05],0)+ ISNULL([06],0)+ ISNULL([07],0)+ ISNULL([08],0)+ ISNULL([09],0)+ ISNULL([10],0)+ ISNULL([11],0)+ ISNULL([12],0))Tong"
        sql &= " INTO #tbLoiNhuanThuc"
        sql &= " FROM"
        sql &= " 	(SELECT NULL AS IDTakeCare, N'Tổng lợi nhuận' AS Ten,(ISNULL(#tbTongLN.[01],0)-ISNULL(#tbChiPhi.[01],0)) AS [01],"
        sql &= " 	(ISNULL(#tbTongLN.[02],0)-ISNULL(#tbChiPhi.[02],0)) AS [02],(ISNULL(#tbTongLN.[03],0)-ISNULL(#tbChiPhi.[03],0)) AS [03],"
        sql &= " 	(ISNULL(#tbTongLN.[04],0)-ISNULL(#tbChiPhi.[04],0)) AS [04],(ISNULL(#tbTongLN.[05],0)-ISNULL(#tbChiPhi.[05],0)) AS [05],"
        sql &= " 	(ISNULL(#tbTongLN.[06],0)-ISNULL(#tbChiPhi.[06],0)) AS [06],(ISNULL(#tbTongLN.[07],0)-ISNULL(#tbChiPhi.[07],0)) AS [07],"
        sql &= " 	(ISNULL(#tbTongLN.[08],0)-ISNULL(#tbChiPhi.[08],0)) AS [08],(ISNULL(#tbTongLN.[09],0)-ISNULL(#tbChiPhi.[09],0)) AS [09],"
        sql &= " 	(ISNULL(#tbTongLN.[10],0)-ISNULL(#tbChiPhi.[10],0)) AS [10],(ISNULL(#tbTongLN.[11],0)-ISNULL(#tbChiPhi.[11],0)) AS [11],"
        sql &= " 	(ISNULL(#tbTongLN.[12],0)-ISNULL(#tbChiPhi.[12],0)) AS [12]"
        sql &= " 	FROM #tbTongLN"
        sql &= " 	INNER JOIN #tbChiPhi ON ISNULL(#tbTongLN.IDTakeCare,1) = ISNULL(#tbChiPhi.IDTakeCare,1))tb"

        sql &= " SELECT tb.IDTakeCare,(CASE AZ WHEN 0 THEN NHANSU.Ten ELSE N' ' END)Ten,[01], [02], [03], [04], [05], [06], [07], [08], [09], [10], [11], [12],Tong"
        sql &= " INTO #tbM"
        sql &= " FROM"
        sql &= " ("
        sql &= " SELECT * FROm #tbDoanhThu"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbLoiNhuan"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbChietKhau"
        sql &= " )tb"
        sql &= " LEFT JOIN NHANSU ON CONVERT(Nvarchar,NHANSU.ID)=tb.IDTakeCare"
        sql &= " ORDER BY tb.IDTakeCare,AZ"

        sql &= " SELECT * FROM #tbM"
        sql &= " UNION ALL"
        sql &= " select * FROM #tbDoanhThuPhong"
        sql &= " UNION ALL"
        sql &= " SELECT NULL AS IDTakeCare,N'Tổng doanh thu' AS Ten, SUM([01]) AS [01] , SUM([02]) AS [02] , SUM([03]) AS [03] , SUM([04]) AS [04] , "
        sql &= " 	SUM([05]) AS [05] , SUM([06]) AS [06] , SUM([07]) AS [07] , SUM([08]) AS [08] , SUM([09]) AS [09] , "
        sql &= " 	SUM([10]) AS [10] , SUM([11]) AS [11] , SUM([12]) AS [12],SUM(Tong)Tong"
        sql &= " FROM #tbDoanhThu"
        sql &= " UNION ALL"
        sql &= " select * FROM #tbLoiNhuanPhong"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbTongLN"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbChietKhauPhong"
        sql &= " UNION ALL"
        sql &= " SELECT NULL AS IDTakeCare,N'Tổng chiết khấu' AS Ten, SUM([01]) AS [01] , SUM([02]) AS [02] , SUM([03]) AS [03] , SUM([04]) AS [04] , "
        sql &= " 	SUM([05]) AS [05] , SUM([06]) AS [06] , SUM([07]) AS [07] , SUM([08]) AS [08] , SUM([09]) AS [09] , "
        sql &= " 	SUM([10]) AS [10] , SUM([11]) AS [11] , SUM([12]) AS [12],SUM(Tong)Tong"
        sql &= " FROM #tbChietKhau"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbChiPhi"
        sql &= " UNION ALL"
        sql &= " SELECT * FROM #tbLoiNhuanThuc"

        sql &= " DROP table #tbM"
        sql &= " DROP table #tbDoanhThu"
        sql &= " DROP table #tbDoanhThuPhong"
        sql &= " DROP table #tbLoiNhuan"
        sql &= " DROP table #tbLoiNhuanPhong"
        sql &= " DROP table #tbChietKhau"
        sql &= " DROP table #tbChietKhauPhong"
        sql &= " DROP table #tbChiPhi"
        sql &= " DROP table #tbTongLN"
        sql &= " DROP table #tbLoiNhuanThuc "

        Dim tb As DataTable = ExecuteSQLDataTable(sql)
        If Not tb Is Nothing Then
            gdvCachMoi.DataSource = tb
        Else
            ShowBaoLoi(LoiNgoaiLe)
        End If
    End Sub


    Private Sub gdvCT_RowStyle(sender As System.Object, e As DevExpress.XtraGrid.Views.Grid.RowStyleEventArgs) Handles gdvCT.RowStyle
        On Error Resume Next
        If e.RowHandle < 0 Then Exit Sub
        If gdvCT.GetRowCellValue(e.RowHandle, "Ten").ToString.Length > 5 Then
            Select Case gdvCT.GetRowCellValue(e.RowHandle, "Ten").ToString.Substring(0, 5)
                Case "   DT", "   LN", "   CK"
                    e.Appearance.Font = New Font(e.Appearance.Font.FontFamily, e.Appearance.Font.Size, FontStyle.Bold)
                Case "Tổng "
                    e.Appearance.Font = New Font(e.Appearance.Font.FontFamily, e.Appearance.Font.Size, FontStyle.Bold)
                    e.Appearance.ForeColor = Color.DarkSlateBlue
            End Select
        End If

    End Sub

    Private Sub rcbPhong_ButtonClick(sender As System.Object, e As DevExpress.XtraEditors.Controls.ButtonPressedEventArgs) Handles rcbPhong.ButtonClick
        If e.Button.Index = 1 Then
            cbPhong.EditValue = Nothing
        End If
    End Sub
End Class